name: CI
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v1
    # - name: Set up Ruby
    #   uses: actions/setup-ruby@v1
    #   with:
    #     ruby-version: '3.3.4'
    - name: Install PostgreSQL Client
      run: sudo apt-get -yqq install libpq-dev postgresql-client sqlite3 libsqlite3-dev firefox
    - name: Install Bundler
      run: sudo gem install bundler
    - name: Install Dependencies
      run: bundle install --path $HOME/.bundle
    - name: Set ENV Variables
      run: |
        echo "PGHOST=localhost" >> $GITHUB_ENV
        echo "PGUSER=postgres" >> $GITHUB_ENV
        echo "RAILS_ENV=test" >> $GITHUB_ENV

    - name: Install dummy app
      run: bundle exec rake test_app
    # - name: Run Tests
    #   run: bundle exec rspec spec
